### ISSUE TITLE
Failed to allocate xxxxx bytes in function 'cv::OutOfMemoryError'

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#212]
在初始化Recognizer时，偶尔会遇到尝试分配很大数量内存导致分配失败的情况。

```plaintext
2023-06-29 10:10:04,051 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-06-29 10:10:04,051 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-06-29 10:10:04,052 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-06-29 10:10:04,879 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-06-29 10:10:05,127 - WARNING - None:45 - start - OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8294400 bytes in function 'cv::OutOfMemoryError'

2023-06-29 10:10:06,127 - ERROR - None:1681 - agent_arrange - init Recognizer failed
Traceback (most recent call last):
  File "arknights_mower\solvers\base_schedule.py", line 1656, in agent_arrange
  File "arknights_mower\solvers\base_schedule.py", line 1384, in choose_agent
  File "arknights_mower\solvers\base_schedule.py", line 1333, in detail_filter
  File "arknights_mower\utils\solver.py", line 103, in tap
  File "arknights_mower\utils\solver.py", line 83, in sleep
  File "arknights_mower\utils\recognize.py", line 53, in update
  File "arknights_mower\utils\recognize.py", line 49, in start
RuntimeError: init Recognizer failed
```

**Comment by Shawnsdaddy** [comment]
这个不会啊 =。=

**Comment by Shawnsdaddy** [comment]
重启模拟器来解决上述问题： 
模拟器支持

- [x] 夜神
- [ ] 其他

**Comment by ZhaoZuohong** [comment]
对于重启模拟器，我有两个想法：

1. 按照一定的时间间隔主动重启。如果已知长时间运行会导致出问题，可以直接定时重启，预防问题发生。
2. 提供重启模拟器的两种模式：一种是运行某进程以启动模拟器、杀死此进程以关闭模拟器；另一种是运行某命令以启动模拟器、运行另一命令以关闭模拟器。允许用户自定义命令，可能可以覆盖绝大多数的情况。

**Comment by Shawnsdaddy** [comment]
成功复现，并且重启成功
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/07e7f4fb-ad46-448e-9980-3a35800052c9)
