### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by MilkWind** [ArkMowers/arknights-mower#265]
日志记录：2023-09-01 11:47:56,798 - ERROR - None:852 - read_screen - (NotFound) Cannot open file C:\Users\111/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.

完整日志：
2023-09-01 11:47:56,806 - ERROR - None:872 - read_time - 读取失败
2023-09-01 11:47:56,807 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-09-01 11:47:56,807 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-01 11:47:56,818 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-01 11:47:57,421 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-09-01 11:47:57,820 - ERROR - None:852 - read_screen - (NotFound) Cannot open file C:\Users\111/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1901)
Traceback (most recent call last):
  File "arknights_mower\solvers\base_schedule.py", line 863, in read_time
ValueError: not enough values to unpack (expected 3, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "arknights_mower\solvers\base_schedule.py", line 814, in read_screen
  File "arknights_mower\solvers\base_schedule.py", line 804, in initialize_paddle
  File "paddleocr\paddleocr.py", line 522, in __init__
    super().__init__(params)
  File "D:\Arknights-Mower\mower-e6430a4-755b207\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "D:\Arknights-Mower\mower-e6430a4-755b207\paddleocr\tools\infer\predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "D:\Arknights-Mower\mower-e6430a4-755b207\paddleocr\tools\infer\utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\111/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1901)

**Comment by ZhaoZuohong** [comment]
这个文件存在吗

**Comment by ZhaoZuohong** [comment]
[paddleocr.zip](https://github.com/ArkMowers/arknights-mower/files/12498050/paddleocr.zip)
飞桨会下载这些东西，你解压放到对应位置试试看

**Comment by MilkWind** [comment]
成功了╮(‵▽′)╭

**Comment by MilkWind** [comment]
> [paddleocr.zip](https://github.com/ArkMowers/arknights-mower/files/12498050/paddleocr.zip) 飞桨会下载这些东西，你解压放到对应位置试试看

对了…这个.paddleocr可以手动配置路径吗？配置时需要注意什么？
我私人用的电脑用户名是中文，但路径似乎不支持包含中文，有没有什么解决办法呀？

**Comment by ZhaoZuohong** [comment]
> 这个.paddleocr可以手动配置路径吗？

这我不知道，不好意思

> 用户名是中文

如果不想动现在的用户，或许可以新建一个用户，用那个用户跑Mower？

**Comment by MilkWind** [comment]
> > 这个.paddleocr可以手动配置路径吗？
> 
> 这我不知道，不好意思
> 
> > 用户名是中文
> 
> 如果不想动现在的用户，或许可以新建一个用户，用那个用户跑Mower？

了解了，我试试(*￣▽￣*)

**Comment by ZhaoZuohong** [comment]
commit 091cff5bdefca6d849e5253c374958789353dd9e 应该支持中文用户名了
