### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch.

### ISSUE THREAD

**Issue by MilkWind** [ArkMowers/arknights-mower#266]
异常信息：InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 3, 20] and the shape of Y = [1, 96, 4, 20]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_add > error]

完整日志：
2023-09-02 19:21:09,154 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-09-02 19:21:09,154 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:09,155 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:09,716 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-09-02 19:21:10,086 - DEBUG - None:293 - find - find: connecting
2023-09-02 19:21:10,087 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/connecting.png
2023-09-02 19:21:10,091 - DEBUG - None:95 - score - match crop: ((960, 864), (1440, 1080)), 6214 -> 98
2023-09-02 19:21:10,099 - DEBUG - None:134 - score - not enough good matches are found: 0 / 361
2023-09-02 19:21:10,099 - DEBUG - None:293 - find - find: double_confirm
2023-09-02 19:21:10,099 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/double_confirm.png
2023-09-02 19:21:10,193 - DEBUG - None:134 - score - not enough good matches are found: 0 / 242
2023-09-02 19:21:10,193 - DEBUG - None:293 - find - find: infra_overview
2023-09-02 19:21:10,193 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/infra_overview.png
2023-09-02 19:21:10,302 - DEBUG - None:171 - score - square is not rectangle: [[32, 242], [4, 364], [254, 326], [251, 285]]
2023-09-02 19:21:10,303 - DEBUG - None:293 - find - find: infra_todo
2023-09-02 19:21:10,303 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/infra_todo.png
2023-09-02 19:21:10,392 - DEBUG - None:71 - match - match fail: (0.1276595744680851, 0.05498276504815793, 0.03125, 0.3624107968757629)
2023-09-02 19:21:10,393 - DEBUG - None:293 - find - find: clue
2023-09-02 19:21:10,393 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/clue.png
2023-09-02 19:21:10,468 - DEBUG - None:171 - score - square is not rectangle: [[783, 887], [959, 971], [1377, 685], [800, 926]]
2023-09-02 19:21:10,469 - DEBUG - None:293 - find - find: arrange_check_in
2023-09-02 19:21:10,469 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/arrange_check_in.png
2023-09-02 19:21:10,497 - DEBUG - None:134 - score - not enough good matches are found: 0 / 72
2023-09-02 19:21:10,497 - DEBUG - None:293 - find - find: arrange_check_in_on
2023-09-02 19:21:10,498 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/arrange_check_in_on.png
2023-09-02 19:21:10,624 - DEBUG - None:77 - match - match success: (0.5392857142857143, 0.7823690686907087, 0.75, 0.7092560180528837)
2023-09-02 19:21:10,624 - DEBUG - None:108 - save_screenshot - remove screenshot: 20230902184333.png
2023-09-02 19:21:10,626 - DEBUG - None:113 - save_screenshot - save screenshot: 20230902192110.png
2023-09-02 19:21:10,626 - INFO - None:268 - get_infra_scene - Scene: 205: 基建放大查看
2023-09-02 19:21:10,627 - DEBUG - None:98 - send_keyevent - keyevent: 4
2023-09-02 19:21:10,628 - DEBUG - None:134 - run - command: input keyevent 4
2023-09-02 19:21:10,628 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:10,639 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:10,674 - DEBUG - None:150 - run - response: b''
2023-09-02 19:21:11,676 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-09-02 19:21:11,676 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:11,677 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:12,223 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-09-02 19:21:12,584 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-09-02 19:21:12,584 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:12,586 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:13,183 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-09-02 19:21:13,552 - DEBUG - None:293 - find - find: connecting
2023-09-02 19:21:13,553 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/connecting.png
2023-09-02 19:21:13,557 - DEBUG - None:95 - score - match crop: ((960, 864), (1440, 1080)), 7890 -> 312
2023-09-02 19:21:13,573 - DEBUG - None:150 - score - calculated transformation matrix failed
2023-09-02 19:21:13,573 - DEBUG - None:293 - find - find: double_confirm
2023-09-02 19:21:13,573 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/double_confirm.png
2023-09-02 19:21:13,689 - DEBUG - None:134 - score - not enough good matches are found: 0 / 242
2023-09-02 19:21:13,690 - DEBUG - None:293 - find - find: infra_overview
2023-09-02 19:21:13,690 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/infra_overview.png
2023-09-02 19:21:13,859 - DEBUG - None:77 - match - match success: (0.881578947368421, 0.915520995305473, 0.75, 0.8584496942476586)
2023-09-02 19:21:13,860 - DEBUG - None:108 - save_screenshot - remove screenshot: 20230902192008.png
2023-09-02 19:21:13,862 - DEBUG - None:113 - save_screenshot - save screenshot: 20230902192113.png
2023-09-02 19:21:13,862 - INFO - None:268 - get_infra_scene - Scene: 201: 基建全局视角
2023-09-02 19:21:13,862 - DEBUG - None:293 - find - find: control_central
2023-09-02 19:21:13,862 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/control_central.png
2023-09-02 19:21:14,158 - DEBUG - None:77 - match - match success: (0.875, 0.9555520186057458, 0.96875, 0.6939416549783637)
2023-09-02 19:21:14,159 - DEBUG - None:262 - base - segment.base: {'central': array([[ 971,   73],
       [ 971,  367],
       [1583,  367],
       [1583,   73]]), 'dormitory_1': array([[ 971,  392],
       [ 971,  526],
       [1425,  526],
       [1425,  392]]), 'dormitory_2': array([[1129,  551],
       [1129,  685],
       [1583,  685],
       [1583,  551]]), 'dormitory_3': array([[ 971,  710],
       [ 971,  844],
       [1425,  844],
       [1425,  710]]), 'dormitory_4': array([[1129,  869],
       [1129, 1003],
       [1583, 1003],
       [1583,  869]]), 'factory': array([[1844,  392],
       [1844,  526],
       [2141,  526],
       [2141,  392]]), 'meeting': array([[1686,  233],
       [1686,  367],
       [2141,  367],
       [2141,  233]]), 'contact': array([[1844,  551],
       [1844,  685],
       [2141,  685],
       [2141,  551]]), 'train': array([[1844,  710],
       [1844,  844],
       [2141,  844],
       [2141,  710]]), 'room_1_3': array([[574, 392],
       [574, 526],
       [869, 526],
       [869, 392]]), 'room_1_2': array([[255, 392],
       [255, 526],
       [550, 526],
       [550, 392]]), 'room_1_1': array([[-64, 392],
       [-64, 526],
       [231, 526],
       [231, 392]]), 'room_2_3': array([[413, 551],
       [413, 685],
       [708, 685],
       [708, 551]]), 'room_2_2': array([[ 94, 551],
       [ 94, 685],
       [389, 685],
       [389, 551]]), 'room_2_1': array([[-225,  551],
       [-225,  685],
       [  70,  685],
       [  70,  551]]), 'room_3_3': array([[574, 710],
       [574, 844],
       [869, 844],
       [869, 710]]), 'room_3_2': array([[255, 710],
       [255, 844],
       [550, 844],
       [550, 710]]), 'room_3_1': array([[-64, 710],
       [-64, 844],
       [231, 844],
       [231, 710]])}
2023-09-02 19:21:14,159 - DEBUG - None:136 - tap - tap: (0, 392)
2023-09-02 19:21:17,230 - DEBUG - None:134 - run - command: screencap -p 2>/dev/null
2023-09-02 19:21:17,230 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:17,242 - DEBUG - None:12 - __init__ - server: ('127.0.0.1', 5037), timeout: 5
2023-09-02 19:21:17,749 - DEBUG - None:50 - __init__ - Matcher init: shape ((1080, 1920))
2023-09-02 19:21:18,113 - DEBUG - None:293 - find - find: control_central
2023-09-02 19:21:18,113 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/control_central.png
2023-09-02 19:21:18,362 - DEBUG - None:71 - match - match fail: (0.046232876712328765, 0.9068884299351618, 0.09375, 0.3606917396140542)
2023-09-02 19:21:18,362 - DEBUG - None:293 - find - find: room_detail
2023-09-02 19:21:18,362 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/room_detail.png
2023-09-02 19:21:18,519 - DEBUG - None:77 - match - match success: (0.9642857142857143, 0.8530682389959326, 0.96875, 0.91257071147536)
2023-09-02 19:21:18,519 - DEBUG - None:293 - find - find: room_detail
2023-09-02 19:21:18,519 - DEBUG - None:28 - loadimg - D:\Arknights-Mower\mower-e6430a4-755b207\arknights_mower\__init__/resources/room_detail.png
2023-09-02 19:21:18,680 - DEBUG - None:77 - match - match success: (0.9642857142857143, 0.8530682389959326, 0.96875, 0.91257071147536)
2023-09-02 19:21:18,696 - ERROR - None:852 - read_screen - In user code:

    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpmmf1gn4e.py", line 29, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 82, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/necks/db_fpn.py", line 247, in forward
      in5, scale_factor=2, mode="nearest", align_mode=1)  # 1/16
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 3, 20] and the shape of Y = [1, 96, 4, 20]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_add > error]
Traceback (most recent call last):
  File "arknights_mower\solvers\base_schedule.py", line 815, in read_screen
  File "paddleocr\paddleocr.py", line 554, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "D:\Arknights-Mower\mower-e6430a4-755b207\paddleocr\tools\infer\predict_system.py", line 95, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "D:\Arknights-Mower\mower-e6430a4-755b207\paddleocr\tools\infer\predict_rec.py", line 609, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpmmf1gn4e.py", line 29, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 82, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/necks/db_fpn.py", line 247, in forward
      in5, scale_factor=2, mode="nearest", align_mode=1)  # 1/16
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 3, 20] and the shape of Y = [1, 96, 4, 20]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_add > error]
2023-09-02 19:21:18,698 - ERROR - None:1754 - agent_arrange - 25
Traceback (most recent call last):
  File "arknights_mower\solvers\base_schedule.py", line 1692, in agent_arrange
  File "arknights_mower\solvers\base_schedule.py", line 1665, in refresh_current_room
  File "arknights_mower\utils\pipe.py", line 3, in func_dec
  File "arknights_mower\solvers\base_schedule.py", line 1629, in get_agent_from_room

分辨率应该没问题
![image](https://github.com/ArkMowers/arknights-mower/assets/115831439/7e7f2539-8e11-48e7-93c1-2797ec341864)

**Comment by Shawnsdaddy** [comment]
没见过的错误增加了.jpg

**Comment by ZhaoZuohong** [comment]
我们现在已经不用PaddleOCR了
