### ISSUE TITLE
软件打开报错

### ISSUE THREAD

**Issue by NULLlnull** [ArkMowers/arknights-mower#284]
Traceback (most recent call last):
  File "webview_ui.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "server.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "arknights_mower\__init__.py", line 9, in <module>
  File "pathlib.py", line 1181, in resolve
  File "pathlib.py", line 206, in resolve
OSError: [WinError 1] 函数不正确。: 'R:\\Temp\\_MEI60362\\arknights_mower\\__init__'

我使用了内存盘。系统的缓存地址是指向内存盘R盘的

**Comment by ZhaoZuohong** [comment]
你运行的是哪个版本
