### ISSUE TITLE
Windows11 下无法打开程序界面

### ISSUE THREAD

**Issue by Kherrisan** [ArkMowers/arknights-mower#536]
程序在任务栏有小图标，但是无法显示程序界面，报错如下：

Traceback (most recent call last):
  File "toolbox.py", line 103, in <module>
  File "webview\__init__.py", line 155, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\zdk\mower\_internal\pythonnet\runtime\Python.Runtime.dll

**Comment by ZhaoZuohong** [comment]
请问是怎样安装 mower 的？

**Comment by Kherrisan** [comment]
从 github release 下载 v3.4.4 的 zip，然后找了一个目录解压的。

顺便，因为目录名称好像被 github 转义错了，我重新贴一下：`RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\zdk\mower\_internal\pythonnet\runtime\Python.Runtime.dll`

**Comment by ZhaoZuohong** [comment]
试一下更新器（[源码](https://github.com/Funny-ppt/MowerUpdater/)，[可执行程序](https://mower.zhaozuohong.vip/Mower%E6%9B%B4%E6%96%B0%E5%99%A8.exe)）？更新器会自动安装所需依赖。

**Comment by Kherrisan** [comment]
用更新器完成更新之后（4/14的版本），又出现新的错误：
[报错截图](https://picgo.kendrickzou.com/images/202404142243289.jpg)

**Comment by ZhaoZuohong** [comment]
我不用 Windows，无法提供更多帮助。
