### ISSUE TITLE
公开招募任务结束后-循环报错

### ISSUE THREAD

**Issue by 1353587086** [ArkMowers/arknights-mower#556]
在Mower中勾选了大型任务-集成战略后，等待其他任务执行完成、轮到启动大型任务时，循环报错，产生海量错误日志，主要报错内容如下：
2024-04-22 16:51:55,306 - ERROR - arknights_mower\__main__.py:530 - simulate - 程序出错--->index -1 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "arknights_mower\__main__.py", line 408, in simulate
  File "arknights_mower\__main__.py", line 399, in _is_depotscan
  File "pandas\core\indexing.py", line 1096, in __getitem__
  File "pandas\core\frame.py", line 3868, in _get_value
IndexError: index -1 is out of bounds for axis 0 with size 0

补充一下，关掉大型任务-集成战略，也会在公开招募任务结束后报错。
[runtime20.log](https://github.com/ArkMowers/arknights-mower/files/15061164/runtime20.log)

**Comment by 1353587086** [comment]
似乎是仓库识别的问题，关掉仓库识别后，不再报错，可以正常进入大型任务

**Comment by 1353587086** [comment]
翻了一下群记录，定位到是因为多开mower，第二个mower的仓库识别文件（depotresult.csv）格式错误，将第一个mower的仓库识别文件结果复制到第二个mower下，就不再报错了
[depotresult.csv](https://github.com/ArkMowers/arknights-mower/files/15065757/depotresult.csv)

**Comment by fuyn101** [comment]
没有表头 回头修

**Comment by fuyn101** [comment]
https://github.com/ArkMowers/arknights-mower/pull/563
